name: czr005
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cmake
  - ninja
  - make
  - git
  - cxx-compiler
  - pybind11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyyaml
  - networkx
  - tqdm
  - pytest
  - pytest-cov
  - scikit-learn
  - statsmodels
  - pip
  - pip:
      - gymnasium

