"""G4IRSF17 local-state and offline source-order research package."""

from .aliasing import (
    AliasingMetrics,
    compare_state_aliasing,
    feature_ablation,
    feature_group_ablation,
    nearest_neighbor_aliasing,
    run_state_aliasing_audit,
)
from .features import (
    AUGMENTED_WITH_LEGACY_FEATURES,
    CANONICAL_OBSERVATION_FEATURES,
    CANDIDATE_FEATURES,
    CONTEXT_FEATURES,
    LEGACY_29_FEATURES,
    PAIRWISE_FEATURES,
    FeatureSpec,
    LocalFeatureError,
    assert_strictly_local_feature_names,
    canonical_feature_vector,
    canonical_source_front_observation,
    pairwise_feature_vector,
)
from .metrics import (
    bucket_generalization_metrics,
    calibration_metrics,
    evaluate_policy,
    evaluate_policy_families,
    ranking_metrics,
    selective_override_metrics,
    system_utility,
)
from .models import PairwiseLinearRanker, TinyMLPListwiseRanker
from .policies import (
    BaselineDecision,
    LocalizedThesisPriority,
    LocalPriorityCandidate,
    current_priority_baseline,
    fifo_baseline,
)
from .selection import (
    ConservativeSelectiveOverride,
    FeatureEnvelope,
    OverrideDecision,
    OverrideEvidence,
    PlattCalibrator,
    expected_calibration_error,
)
from .splits import (
    DEFAULT_FRACTIONS,
    SPLIT_NAMES,
    DiagnosticSplits,
    chronological_time_split,
    deterministic_group_split,
    group_overlap_count,
    make_diagnostic_splits,
    rows_for_split,
)
from .temporal import (
    DEFAULT_WINDOWS_SECONDS,
    BoundedTemporalCounter,
    SourceTemporalCounters,
    bounded_window_counts,
)
from .training import (
    LinearUtilityRegressor,
    PhaseDTrainingConfig,
    PhaseDTrainingResult,
    load_effect_feature_rows,
    train_g4irsf17_i1,
    train_phase_d,
    write_phase_d_artifacts,
)

__all__ = [
    "AUGMENTED_WITH_LEGACY_FEATURES",
    "AliasingMetrics",
    "BaselineDecision",
    "BoundedTemporalCounter",
    "CANONICAL_OBSERVATION_FEATURES",
    "CANDIDATE_FEATURES",
    "CONTEXT_FEATURES",
    "ConservativeSelectiveOverride",
    "DEFAULT_FRACTIONS",
    "DEFAULT_WINDOWS_SECONDS",
    "DiagnosticSplits",
    "FeatureEnvelope",
    "FeatureSpec",
    "LEGACY_29_FEATURES",
    "LinearUtilityRegressor",
    "LocalFeatureError",
    "LocalPriorityCandidate",
    "LocalizedThesisPriority",
    "OverrideDecision",
    "OverrideEvidence",
    "PAIRWISE_FEATURES",
    "PairwiseLinearRanker",
    "PhaseDTrainingConfig",
    "PhaseDTrainingResult",
    "PlattCalibrator",
    "SPLIT_NAMES",
    "SourceTemporalCounters",
    "TinyMLPListwiseRanker",
    "assert_strictly_local_feature_names",
    "bounded_window_counts",
    "bucket_generalization_metrics",
    "calibration_metrics",
    "canonical_feature_vector",
    "canonical_source_front_observation",
    "chronological_time_split",
    "compare_state_aliasing",
    "current_priority_baseline",
    "deterministic_group_split",
    "evaluate_policy",
    "evaluate_policy_families",
    "expected_calibration_error",
    "feature_ablation",
    "feature_group_ablation",
    "fifo_baseline",
    "group_overlap_count",
    "load_effect_feature_rows",
    "make_diagnostic_splits",
    "nearest_neighbor_aliasing",
    "pairwise_feature_vector",
    "ranking_metrics",
    "rows_for_split",
    "run_state_aliasing_audit",
    "selective_override_metrics",
    "system_utility",
    "train_g4irsf17_i1",
    "train_phase_d",
    "write_phase_d_artifacts",
]
